### ISSUE TITLE
不能成功引入，错误如下：

### ISSUE THREAD

**Issue by xinyangmaojian** [Cazaea/SweetAlertDialog#1]
Error:(48, 20) Failed to resolve: com.github.cazaea:sweet-alert-dialog:1.0.0
Show in File
Show in Project Structure dialog

**Comment by xinyangmaojian** [comment]
噢  不好意思  是我引入依赖时少看了一句话      没事的   仔细的按照readme里的方法做就可以正常用的

**Comment by Cazaea** [comment]
祝你使用愉快！
